import './js/mobile-menu';
import './js/theme-switch';
import './js/hero';
import './js/all-cat';
import './js/popular';
import './js/modals/modal-rating';
import './js/modals/modal-order';
import './js/modals/modal-recipes';
import './js/search';
import './js/cart/cart';
import './js/all-cat/reset';
import './js/scroll';
import './js/modals/open-rating';
import './js/search/pagination-search';
// test
